name: breakpad-win

on:
    workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-2019, platform: x64, vs: 2019 }

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      VS_VERSION: ${{ matrix.config.vs }}
      PLATFORM: ${{ matrix.config.platform }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
    
      - name: Check out breakpad
        shell: cmd
        run: |
          git clone --depth=1 https://github.com/hxbb00/qtwebengine-opensource-src.git C:\_work
          
      - name: Check out cmakelists
        shell: cmd
        run: |
          git clone https://github.com/hxbb00/breakpad-lite.git C:\_work2
        
      - uses: lukka/get-cmake@latest

      - name: Environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
          :: Loop over all environment variables and make them global using set-env.
          :: See: https://stackoverflow.com/a/39184941
          setlocal
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo ::set-env name=%%a::%%b
          )
          endlocal

      - name: copy cmakelists
        shell: bash
        run: cp -r C:/_work2/breakpad_build4w C:/_work/src/3rdparty/chromium/third_party/breakpad/breakpad
          
      - name: cmake
        shell: cmd
        run: cmake .
        working-directory: C:\_work\            src\3rdparty\chromium\third_party\breakpad\breakpad\breakpad_build4w

      - name: msbuild
        shell: cmd
        run: msbuild breakpad.sln
        working-directory: C:\_work\            src\3rdparty\chromium\third_party\breakpad\breakpad\breakpad_build4w
        