name: breakpad-win

on:
    workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-2019, platform: x64, vs: 2019 }

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      VS_VERSION: ${{ matrix.config.vs }}
      PLATFORM: ${{ matrix.config.platform }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
    
      - uses: actions/checkout@v3 
        with: 
          repository: hxbb00/qtwebengine-opensource-src
          sparse-checkout: | 
            src/3rdparty/chromium/third_party/breakpad
             
      - name: Check out breakpad Cmakelists
        shell: cmd
        run: |
          git clone https://github.com/hxbb00/breakpad-lite.git C:\_work2
        
      - uses: lukka/get-cmake@latest

      - name: copy cmakelists
        shell: bash
        run: |
          cp -r C:/_work2/breakpad_build4w ./src/3rdparty/chromium/third_party/breakpad/breakpad
          ls -al ./src/3rdparty/chromium/third_party/breakpad/breakpad
          
      - name: cmake
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\%VS_VERSION%\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
          cmake .
          msbuild breakpad.sln -p:Configuration=Release
        working-directory: ${{ github.workspace }}\src\3rdparty\chromium\third_party\breakpad\breakpad\breakpad_build4w

      - name: pack files 
        shell: cmd
        run: 7z a breakpad_win_dev.zip ./src/3rdparty/chromium/third_party/breakpad/breakpad/breakpad_build4w/Release
  
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
    
      - name: Release 
        uses: softprops/action-gh-release@v1 
        with: 
          name: breakpad_win_dev 
          tag_name: ${{ env.RELEASE_DATE }} 
          files: breakpad_win_dev.zip
        
