name: CI-with-docker

on:
    workflow_dispatch:

jobs:
  buildx64-on-docker:
    runs-on: ubuntu-20.04
    container:
      image: 'ghcr.io/hxbb00/ubuntu1604:main'
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    env:
      CC: gcc
      CXX: g++
      PLATFORM: x64
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          uname -a
          cat /proc/version
          pwd
          ls -al "${PWD}"
          echo "apt-get install gcc 4.8"
          sudo apt-get install -q -y --no-install-recommends gcc-4.8 g++-4.8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++
          gcc -v
          cd ./src
          echo "download"
          wget https://github.com/hxbb00/qtwebengine-opensource-src/releases/download/1.0/breakpad_dev_x86_64.zip -O breakpad_dev.zip
          mkdir -p ./breakpad_dev && unzip breakpad_dev.zip -d ./breakpad_dev
          echo "configure"
          cmake .
          echo "make"
          make
          echo "make install"
          make install
          cp -R ./output /breakpad_output

      - uses: actions/upload-artifact@v3
        with:
          name: breakpad_lite_x86_64
          path: |
            /breakpad_output
